### ISSUE TITLE
Request to change link on bug report button

### ISSUE THREAD

**Issue by shuLhan** [devygo/tour#3]
Currently, the go-tour-th.appspot.com link the bug report button to official (English) Go Tour repository.  This may cause many issues related to this tour translation get reported to golang/tour instead of here [1].

To change the bug report link, edit the `github-repo` value [2] to reference this repository and re-deploy the application.

If this is not the repository for go-tour-th.appspot.com please ignore this issue or forward it to the correct one.

Thank you,
Shulhan

[1] https://github.com/golang/tour/issues/550
[2] https://github.com/golang/tour/blob/master/static/js/values.js#L52

**Comment by chonla** [comment]
Fixed in 113f891480e73c52090806f90c9c5386efcc7ed0.
